name: Redis Practice

on:
  workflow_dispatch:

jobs:
  redis-practice:
    runs-on: ubuntu-latest

    steps:
      - name: Install redis
        run: sudo apt-get install -y redis-tools redis-server
      - name: Connect to redis cli
        run: |
          redis-cli  ping
      - name: String as key type
        run: |
          redis-cli set name "abhi"
          redis-cli get name
