name: Redis Practice

on:
  workflow_dispatch:

jobs:
  redis-practice:
    runs-on: ubuntu-latest

    steps:
      - name: Install redis
        run: sudo apt-get install redis-tools redis-server
        
      - name: Connect to redis cli
        run: redis-cli  ping
        
      - name: Set and get String as key type
        run: |
          redis-cli set name "abhi"
          redis-cli get name

      - name: Set and get hash as key type
        run: |
          redis-cli hset student id 1 name "abhi"
          redis-cli hgetall student
          redis-cli hget student id
          redis-cli hget student name
          
          
